### ISSUE TITLE
CSS property `height: 100%` does not work

### ISSUE THREAD

**Issue by WenchuanLiliZhao** [WenchuanLiliZhao/A-Little-History-of-Telescopes#7]
The following CSS worked well before I added `<!DOCTYPE html>` whose absence causes some loading problems.

```css
.class {
  height: 100%;
}
```

But once `<!DOCTYPE html>` was added, the height property failed to work. Essentially, every height value with `%` as the unit became zero...

**Comment by WenchuanLiliZhao** [comment]
Use this instead of above

```css
.class {
  height: 100hv;
}
```
